services:
  cache:
    image: varnish:alpine
    restart: unless-stopped
    volumes:
      - "./default.vcl:/etc/varnish/default.vcl"
    tmpfs:
      - /app:exec
    environment:
      - VARNISH_SIZE=512M
  site:
    build: .
    restart: unless-stopped
    depends_on:
      - varnish
    
    